// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ctwaPk3_FjRNT7ezjIMl-sjdppTg5Tk',
    appId: '1:7138187439:web:8272cf889f2c861d4c1c5a',
    messagingSenderId: '7138187439',
    projectId: 'pos-billing-app-ajith',
    authDomain: 'pos-billing-app-ajith.firebaseapp.com',
    storageBucket: 'pos-billing-app-ajith.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUl7JHhE7RjgaR2K5_AgKehunMO9NAjg',
    appId: '1:7138187439:android:035aaaee362d5b1d4c1c5a',
    messagingSenderId: '7138187439',
    projectId: 'pos-billing-app-ajith',
    storageBucket: 'pos-billing-app-ajith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPDf__SaAtBYF7oH0AELkjMOIu0et3Jjw',
    appId: '1:7138187439:ios:4313983d3f0f0cb34c1c5a',
    messagingSenderId: '7138187439',
    projectId: 'pos-billing-app-ajith',
    storageBucket: 'pos-billing-app-ajith.firebasestorage.app',
    iosBundleId: 'com.example.flutterPosBillingApp',
  );

}